import Config

# Configure your database
config :crypto_portfolio_v3, CryptoPortfolioV3.Repo,
  username: "postgres",
  password: "postgres",
  hostname: "localhost",
  database: "crypto_portfolio_v3_dev",
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :crypto_portfolio_v3, CryptoPortfolioV3Web.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {127, 0, 0, 1}],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "RQEEyAfAZqw90Jx4Pl4iTdYMYjShHRjWnq8iXavHu3BeJ5RTJs78/G5kqJkxtcAw",
  watchers: []

# Mailer: preview at http://localhost:4000/dev/mailbox, no real SMTP.
config :crypto_portfolio_v3, CryptoPortfolioV3.Mailer, adapter: Swoosh.Adapters.Local
config :swoosh, :api_client, false

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Enable dev routes for dashboard and mailbox
config :crypto_portfolio_v3, dev_routes: true

# Do not include metadata nor timestamps in development logs
config :logger, :default_formatter, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime
