defmodule CryptoPortfolioV3.Emails do
  @moduledoc """
  Swoosh.Email builders. Each function returns a %Swoosh.Email{} struct —
  no side effects. Delivery is CryptoPortfolioV3.Mailer.deliver/1.
  """

  import Swoosh.Email

  @from_name "abcoins"
  @from_address "noreply@abcoins.xyz"
  @admin_address Application.compile_env(:crypto_portfolio_v3, :admin_email, "noreply@abcoins.xyz")

  @doc """
  Email-verification code sent after registration. `code` is the plain
  6-digit string generated by `Accounts.create_verification_code/1`.
  """
  @spec verification_email(map(), binary()) :: Swoosh.Email.t()
  def verification_email(%{email: email, username: username}, code)
      when is_binary(email) and is_binary(code) do
    new()
    |> to(email)
    |> from({@from_name, @from_address})
    |> subject("abcoins — confirm your email")
    |> text_body("""
    Hi #{username},

    Your verification code is: #{code}

    Enter it on the sign-in page to finish creating your account.
    The code expires in 10 minutes.

    If you didn't sign up, you can ignore this message.

    — abcoins
    """)
  end

  @doc """
  Password-reset code sent in response to a forgot-password request. `code`
  is the plain 6-digit string generated by `Accounts.create_password_reset/1`.
  """
  @spec password_reset_email(map(), binary()) :: Swoosh.Email.t()
  def password_reset_email(%{email: email, username: username}, code)
      when is_binary(email) and is_binary(code) do
    new()
    |> to(email)
    |> from({@from_name, @from_address})
    |> subject("abcoins — reset your password")
    |> text_body("""
    Hi #{username},

    Your password reset code is: #{code}

    Enter it on the sign-in page along with your new password.
    The code expires in 10 minutes.

    If you didn't request a reset, you can ignore this message — your
    password is unchanged.

    — abcoins
    """)
  end

  @doc """
  Contact-form submission. Sends to the configured admin address with
  the visitor's name/email/subject/message inline. `reply_to` is set to
  the visitor so admins can reply directly from their inbox.
  """
  @spec contact_form_email(%{
          name: binary(),
          email: binary(),
          subject: binary(),
          message: binary()
        }) :: Swoosh.Email.t()
  def contact_form_email(%{name: name, email: email, subject: subj, message: msg}) do
    new()
    |> to(@admin_address)
    |> from({@from_name, @from_address})
    |> reply_to(email)
    |> subject("[abcoins contact] " <> subj)
    |> text_body("""
    From: #{name} <#{email}>
    Subject: #{subj}

    #{msg}

    —
    Sent via the abcoins Contact Us form.
    """)
  end
end
